apiVersion: v1
kind: Secret
metadata:
  name: patent-rpa-secrets
  namespace: patent-rpa-system
type: Opaque
data:
  # 注意：這些值需要使用base64編碼
  # 在實際部署時，這些值應該從Azure Key Vault中取得
  # 以下是範例格式，請替換為實際的base64編碼值
  
  # 資料庫密碼
  POSTGRES_PASSWORD: "cGF0ZW50X3NlY3VyZV9wYXNzd29yZA==" # patent_secure_password
  
  # Redis密碼
  REDIS_PASSWORD: "cmVkaXNfc2VjdXJlX3Bhc3N3b3Jk" # redis_secure_password
  
  # Azure服務金鑰
  AZURE_OPENAI_API_KEY: "eW91cl9henVyZV9vcGVuYWlfYXBpX2tleQ==" # your_azure_openai_api_key
  AZURE_SEARCH_API_KEY: "eW91cl9henVyZV9zZWFyY2hfYXBpX2tleQ==" # your_azure_search_api_key
  AZURE_STORAGE_ACCOUNT_KEY: "eW91cl9henVyZV9zdG9yYWdlX2FjY291bnRfa2V5" # your_azure_storage_account_key
  
  # JWT密鑰
  JWT_SECRET_KEY: "eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl" # your_jwt_secret_key_here
  
  # SMTP配置
  SMTP_USERNAME: "eW91cl9lbWFpbEBnbWFpbC5jb20=" # your_email@gmail.com
  SMTP_PASSWORD: "eW91cl9hcHBfcGFzc3dvcmQ=" # your_app_password

---
# Azure Key Vault Secret Provider Class
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: patent-rpa-keyvault-secrets
  namespace: patent-rpa-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "patent-rpa-keyvault"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: PostgresPassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: RedisConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: AcrAdminPassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: StorageConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: SearchApiKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: OpenAiApiKey
          objectType: secret
          objectVersion: ""
    tenantId: "your-tenant-id"
  secretObjects:
  - secretName: patent-rpa-keyvault-secrets
    type: Opaque
    data:
    - objectName: PostgresPassword
      key: postgres-password
    - objectName: RedisConnectionString
      key: redis-connection-string
    - objectName: StorageConnectionString
      key: storage-connection-string
    - objectName: SearchApiKey
      key: search-api-key
    - objectName: OpenAiApiKey
      key: openai-api-key
